steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['config', 'user.name', 'FreshTracks Cloud Builder']
- name: 'gcr.io/cloud-builders/git'
  args: ['config', 'user.email', 'info@freshtracks.io']
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', '--all']
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', '$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/git'
  args: ['merge', '--no-edit', 'grpc-streaming-open-tracing']
- name: 'gcr.io/cloud-builders/git'
  args: ['merge', '--no-edit', 'bigtable-index-query-speedup']
- name: 'gcr.io/genuine-cat-188717/docker-with-make'
  args: ['all']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-configs', 'gcr.io/$PROJECT_ID/cortex-configs:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-lite', 'gcr.io/$PROJECT_ID/cortex-lite:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-table-manager', 'gcr.io/$PROJECT_ID/cortex-table-manager:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-querier', 'gcr.io/$PROJECT_ID/cortex-querier:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-ruler', 'gcr.io/$PROJECT_ID/cortex-ruler:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-ingester', 'gcr.io/$PROJECT_ID/cortex-ingester:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-distributor', 'gcr.io/$PROJECT_ID/cortex-distributor:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'quay.io/weaveworks/cortex-alertmanager', 'gcr.io/$PROJECT_ID/cortex-alertmanager:$BRANCH_NAME-$SHORT_SHA']
images: [
  'gcr.io/$PROJECT_ID/cortex-configs:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-lite:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-table-manager:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-querier:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-ruler:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-ingester:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-distributor:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/cortex-alertmanager:$BRANCH_NAME-$SHORT_SHA',
]

      

